# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='model_pic',
            field=models.ImageField(default=b'blog/images/already.png', upload_to=b'templates'),
        ),
    ]
